### ISSUE TITLE
Cipher.DoFinal() exception

### ISSUE THREAD

**Issue by Skenja** [xamarin/monodroid-samples#179]
Hello!

I'm trying to implement fingerprint authentication in my application, and I followed this guide 1:1. 
I'm testing it on a OnePlus 3 in debug mode, with debug keystore, through Visual Studio 2015.
I am having issues with CryptoObjectHelper, specifically with 
"result.CryptoObject.Cipher.DoFinal(SECRET_BYTES);" from "MyAuthCallbackSample".
What are those SECRET_BYTES suppoused to be? I don't see them anywhere else.
It always throws "Java.Lang.IllegalStateException: Cipher not initialized for encryption/decryption", even tho CryptoObjectHelper is a blatant copy of the guide.

My logic tells me since AES is a symetric encryption method, it's only logical that these secret bytes would have something to do with the input, but what is the input and where is it set?

This is stack trace:

{Java.Lang.IllegalStateException: Cipher not initialized for encryption/decryption
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4009/3570b3eb/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143
 at Java.Interop.JniEnvironment+InstanceMethods.CallNonvirtualObjectMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x000a8] in /Users/builder/data/lanes/4009/3570b3eb/source/Java.Interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:11687
 at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeNonvirtualObjectMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x00022] in /Users/builder/data/lanes/4009/3570b3eb/source/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:365
 at Javax.Crypto.Cipher.DoFinal (System.Byte[] input) [0x0001e] in /Users/builder/data/lanes/4009/3570b3eb/source/monodroid/src/Mono.Android/platforms/android-25/src/generated/Javax.Crypto.Cipher.cs:178
 at MyApp.Infrastructure.FingerprintAuthCallbackHandler.OnAuthenticationSucceeded (Android.Support.V4.Hardware.Fingerprint.FingerprintManagerCompat+AuthenticationResult result) [0x00018] in C:\Users\TheUser\Repos\MyApp\Projects\Mobile.Xamarin\MyApp.Mobile.Android\Infrastructure\FingerprintAuthCallbackHandler.cs:28
 --- End of managed Java.Lang.IllegalStateException stack trace ---

java.lang.IllegalStateException: Cipher not initialized for encryption/decryption
    at javax.crypto.Cipher.checkCipherState(Cipher.java:1645)
    at javax.crypto.Cipher.doFinal(Cipher.java:2048)
    at md55e891c0eb508e3fd07a713291fe50803.FingerprintAuthCallbackHandler.n_onAuthenticationSucceeded(Native Method)
    at md55e891c0eb508e3fd07a713291fe50803.FingerprintAuthCallbackHandler.onAuthenticationSucceeded(FingerprintAuthCallbackHandler.java:32)
    at android.support.v4.hardware.fingerprint.FingerprintManagerCompat$Api23FingerprintManagerCompatImpl$1.onAuthenticationSucceeded(FingerprintManagerCompat.java:301)
    at android.support.v4.hardware.fingerprint.FingerprintManagerCompatApi23$1.onAuthenticationSucceeded(FingerprintManagerCompatApi23.java:96)
    at android.hardware.fingerprint.FingerprintManager$MyHandler.sendAuthenticatedSucceeded(FingerprintManager.java:876)
    at android.hardware.fingerprint.FingerprintManager$MyHandler.handleMessage(FingerprintManager.java:824)
   at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6209)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
}

**Comment by gkowieski** [comment]
@Skenja , I'm pretty sure that's the salt.  For almost any encryption method, you provide a "salt" to make your encryption unique to you.  Basically it's your password to your encryption.  For example, albeit simple, if I use "greg" as my salt the encryption may return "093ln;ladk7)(*&^*&" as the encrypted key.  whereas if I salt with "greg2" the encryption method may return "":LKJjOKUT*&^)ojk)(&*^" as the encrypted key.

Hope that helps.

**Comment by Skenja** [comment]
@gkowieski Thank you for the quick answer.
Perhaps I'm not understanding my problem correctly than. Let me lay it out and perhaps someone sees the flaw:
1) CryptoObjectHelper fetches some value from the keystore, and initializes a cipher with that value
2) The cipher is passed in as a parameter to CryptoObject
3) The resulting CryptoObject is passed in to the method Authenticate on FingerprintManager
4) Once successful scanning of the fingerprint occurs, CallbackHandlers OnSuccess method recieves a result containing a cipher as well (assuming it to be the one passed in earlier)
5) When calling DoFinal(byte[] input) on that cipher, exception occurs -> cipher not initialized

What gives? Whats wrong here?

**Comment by gkowieski** [comment]
Unfortunately, I haven't used that method or class, so I'd be talking out of my butt.

**Comment by Skenja** [comment]
I figured it out. In the guide CryptoObjectHelper is refactored, in method CreateCipher where the cipher was initialized, bitwise or is used to set flags, which cannot work because the enum is not prepared for it (values go 1, 2, 3, 4 instead of 1, 2, 4, 8). In this repository it had been fixed, but the guide contains the old code so that is where the problem came from.

**Comment by YigitCiray** [comment]
Hi Skenja,

I do not understand the solution. Is it possible for you to explain little bit more. Thank you very much.
